[build]
  base = "."
  publish = "out"
  command = "npm run build && npm run export"
  functions = "netlify/functions"


[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
