import type { Metadata } from "next";
import styles from "./layout.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={styles.childrenWrap}>
        <div className={styles.appTop}>
          <div>
          <a href="/contact">CONTACT</a></div>
        </div>
        <div className={styles.maxWidth}>
          {children}
        </div>
      </body>
    </html>
  );
}
