import type { Metadata } from "next";
import styles from "./layout.module.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={styles.childrenWrap}>
        <div className={styles.appTop}>
          <Link href="/">
            <svg
              width="512"
              height="512"
              viewBox="0 0 512 512"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M131 183V451.5"
                stroke="#FCEFC9"
                stroke-width="30"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
              <path
                d="M384 52L384 317"
                stroke="#FCEFC9"
                stroke-width="30"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
              <circle
                cx="257.5"
                cy="255.5"
                r="126.5"
                stroke="#FCEFC9"
                stroke-width="30"
              />
              <path
                d="M37 124L480 380"
                stroke="#FCEFC9"
                stroke-width="30"
                stroke-linejoin="round"
              />
              <path
                d="M385 248.5H255"
                stroke="#FCEFC9"
                stroke-width="30"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
              <path
                d="M31 234.604C30.3386 241.647 30 248.784 30 256C30 380.816 131.184 482 256 482C345.559 482 422.949 429.906 459.525 354.367L485.572 369.405C443.753 453.9 356.662 512 256 512C114.615 512 0 397.385 0 256C0 255.132 0.00505475 254.265 0.0136719 253.399L31 234.604ZM256 0C396.076 0 509.873 112.502 511.969 252.079L481.539 270.538C481.844 265.731 482 260.884 482 256C482 131.184 380.816 30 256 30C169.738 30 94.7638 78.3281 56.6768 149.386L30.6807 134.377C73.9658 54.3556 158.635 0 256 0Z"
                fill="#FCEFC9"
              />
            </svg>
          </Link>
          <div>
            <Link href="/contact">CONTACT</Link>
          </div>
        </div>
        <div className={styles.maxWidth}>{children}</div>
      </body>
    </html>
  );
}
